### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by wormen** [Maxlab/stacker#1]
Подскажите, когда ожидать документацию по вашей поделке?

**Comment by Maxlab** [comment]
Документация уже есть, ее расширение пока не планируется, если ее недостаточно можете посмотреть ролики. Если есть вопросы по существу, задавайте, если этого нет в доке как раз и дополним.

**Comment by wormen** [comment]
есть момент, в документации написано
`
*.dev > 127.0.0.1 (if you use boot2docker, use that ip)
`

но boot2docker уже давно не используется, сейчас там используются windows контейнеры(в бета версии) и hyper-v/virtualbox
соответственно настройки будут отличные от тех, что в документации

**Comment by Maxlab** [comment]
Не одна документация не покроет всего того многообразия, чем пользуются разработчики. Считаю,  что текущей документации вполне хвататет для 95% Уже очень многие себе поставили и у них не возникало подобных проблем, да и к слову, что у вас то за проблема? Вы поставить не можете? Тогда, может быть, стоит задавать вопросы по существу проблемы. Постарались бы решить, а уже решением дополнили доку, как вы хотели. 

С другой стороны, если проблем нет, но вы обладаете зананиями, которыми моглибы дополнить документацию - то создайте пуллреквест, всегда будем рады.

**Comment by wormen** [comment]
проблем с установкой не возникло, все нормально
но в работе контейнера **nginx** наблюдается ошибка #3

**Comment by Maxlab** [comment]
Не по теме пишете. Ответил, это не к нам.
