### ISSUE TITLE
Error stacker

### ISSUE THREAD

**Issue by SolidRhino** [Maxlab/stacker#10]
Stacker error on running stacker

`stacker usage
sed: illegal option -- s
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- s
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- s
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Usage stacker [build console down exec logs mysql mysqldump php ps restart rm start stop up]`

         Name                      Command                          State    Ports

         php7console               docker-php-entrypoint php-fpm    Up       9000/tcp
         stacker_elasticsearch_1   /docker-entrypoint.sh serv ...   Exit 1
         stacker_mailcatcher_1     mailcatcher -f --ip=0.0.0.0      Up       1025/tcp, 1080/tcp
         stacker_mysql_1           docker-entrypoint.sh mysqld      Up       0.0.0.0:3307->3306/tcp
         stacker_pgsql_1           docker-entrypoint.sh postgres    Up       0.0.0.0:5433->5432/tcp
         stacker_php5apache_1      docker-php-entrypoint apac ...   Up       0.0.0.0:444->443/tcp, 0.0.0.0:81->80/tcp
         stacker_php7xdebug_1      docker-php-entrypoint php-fpm    Up       9000/tcp
         stacker_redis_1           docker-entrypoint.sh redis ...   Up       0.0.0.0:6379->6379/tcp
         stacker_web_1             /bin/bash -c envsubst '$SY ...   Up       0.0.0.0:443->433/tcp, 443/tcp, 0.0.0.0:80->80/tcp

I use Mac OS 10.12.3

Thank you

**Comment by Maxlab** [comment]
Was not able to reproduce themselves
![2017-03-21 15 09 24](https://cloud.githubusercontent.com/assets/1397425/24146821/7182d9d4-0e48-11e7-811d-09ef726c7136.png)

Try to put the latest version from the master.

**Comment by Maxlab** [comment]
long time no feedback, so close
