### ISSUE TITLE
Symlinks don't work on mac

### ISSUE THREAD

**Issue by vitr** [Maxlab/stacker#11]
I'm not sure if it's docker or stacker issue, but if I copy the full Laravel project to ./workspace/test/laravel it works just OK, however, when I create a soft link for it (as suggested in the readme)  
`ln -s /your_path/to_your_own_projects ./workspace/test`  
I get 404 Not Found error

**Comment by Maxlab** [comment]
Need more info.

**Comment by vitr** [comment]
so, got a Laravel 5.4 working project, if I copy it to 
`./workspace/test`
it works just great.
if you make a soft link to it, e.g.
`ln -s /your_path/to_your_own_projects/my_laravel_project ./workspace/test`  
it doesn't pick up that link and I get I get 404 Not Found error nginx error

**Comment by Maxlab** [comment]
try 
ln -s /your_path/to_your_own_projects ./workspace

**Comment by Maxlab** [comment]
then, if your my_laravel_project open in browser my_laravel_project.dev

**Comment by Maxlab** [comment]
I think the problem is that you are trying to give a symbolic link to a single project.
Instead, create a link to folder with all your projects and open them all in the browser.
To add a new project(a folder with source codes) do not need to do links.

**Comment by Maxlab** [comment]
Watch examples https://youtu.be/42BemUfK5-4

**Comment by vitr** [comment]
thanks, but this doesn't help, I get 500 Internal server error from nginx.

**Comment by Maxlab** [comment]
Maybe video or scrinshots? I think it would be the fastest.
$ stacker console works? 
If 500, you can send the log in $ stacker logs?

**Comment by Maxlab** [comment]
Try $ service docker restart

**Comment by vitr** [comment]
yep, restart did the trick! stacker console/logs work as well, everything is great, sorry for the troubles. might be useful to include this case in the readme/faq as I was wrongly assuming that you don't need to restart anything

**Comment by Maxlab** [comment]
On MacOS hasn't been tested, so your feedback is valuable. If you want to send their pullrequests on the part of the MacOS.

**Comment by vitr** [comment]
seems my fault, I followed the process again and didn't need a restart, If I create workspace folder as a symlink and after that run stacker, it works as expected. thanks for your help
