### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by Hector68** [Maxlab/stacker#15]
Building php5apache
ERROR: Error processing tar file(archive/tar: invalid tar header):

System: Windown 10 Home; Docker Tools

**Comment by Hector68** [comment]
Ошибка была в правах доступа, склонирвал внутри  Docker Tools, установка прошла нормально. Но теперь при запуске вылетают такие ошибки ` docker-compose up`

php5apache_1     | apache2: Could not open configuration file /etc/apache2/apache2.conf: No such file or directory

web_1            | envsubst: error while reading "standard input": Is a directory

**Comment by Maxlab** [comment]
Что-то с директориями в винде. К сожалению ничем не могу тут помочь, тестировали под линукс и мак, под винду еще не успели.
