### ISSUE TITLE
DB Connection issue - MySQL ERROR 2002 (HY000): Can't connect to local...

### ISSUE THREAD

**Issue by regenrek** [Maxlab/stacker#17]
Hi,

I'm just trying to connect to  stacker_mysql_1 container. I'm using wordpress but I get always the 2002 error.

My Connection Settings are the following:

DB_HOST='127.0.0.1'
DB_NAME='wpdev'
DB_PASSWORD='root'
DB_USER='root'

* I can connect via Sequel Pro to the database via root user - no problem.
* It also works if I use the IP which I get via docker inspect stacker_mysql_1.
But this is a bit annoying since the IP always changes on stacker up/down.
Looks like this here '172.18.0.2'

Oh and btw: I needed to add mysqli extension to the nginx xdebug dockerfile to
get wordpress running.

Regards

**Comment by Maxlab** [comment]
Try for under container
# Example for mysql
  parameters:
    database_host: mysql
    database_port: 3306
    database_name: wpdev
    database_user: root
    database_password: root

For client externally
  parameters:
    database_host: localhost
    database_port: 3307
    database_name: wpdev
    database_user: root
    database_password: root

**Comment by Maxlab** [comment]
The extension will soon add, but if you don't want to wait can add it yourself in dockerfile.
After that you will need to gather again
$ stacker build && stacker down && stacker up && stacker ps

**Comment by regenrek** [comment]
Finally! I tried localhost(:3007) with no luck but not 'mysql' as database host -> this is working!
