### ISSUE TITLE
Service 'php7xdebug' failed to build

### ISSUE THREAD

**Issue by bifidokk** [Maxlab/stacker#18]
In file included from /tmp/pear/temp/intl/php_intl.h:34:0,
                 from /tmp/pear/temp/intl/php_intl.c:25:
/tmp/pear/temp/intl/intl_error.h:24:40: fatal error: ext/standard/php_smart_str.h: No such file or directory
 #include <ext/standard/php_smart_str.h>
                                        ^
compilation terminated.
Makefile:194: recipe for target 'php_intl.lo' failed
make: *** [php_intl.lo] Error 1
ERROR: `make' failed
ERROR: Service 'php7xdebug' failed to build: The command '/bin/sh -c apt-get update     && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone     && apt-get install -f -y --reinstall locales && locale-gen en_US.UTF-8     && apt-get install -y libbz2-dev     && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng12-dev     && apt-get install -y libmcrypt-dev     && apt-get install -y libpq-dev libsqlite3-dev     && apt-get install -y libxslt-dev     && apt-get install -y libicu-dev     && apt-get install -y zlib1g-dev     && apt-get install -y msmtp imagemagick libssl-dev libxml2-dev wget git vim ruby ruby-dev libcurl4-openssl-dev     && pecl install apcu     && echo "extension=apcu.so" > /usr/local/etc/php/conf.d/apcu.ini     && pecl install -o -f redis     && rm -rf /tmp/pear     && echo "extension=redis.so" > /usr/local/etc/php/conf.d/redis.ini     && pecl install intl && docker-php-ext-install intl     && pecl install xdebug     && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)\n" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_autostart=0" >> /usr/local/etc/php/conf.d/xdebug.ini     && echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/xdebug.ini     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && docker-php-ext-install bz2 mcrypt pdo_mysql pdo_pgsql pdo_sqlite xsl zip                         opcache calendar dba pcntl bcmath mbstring xmlrpc ftp shmop     && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*' returned a non-zero code: 1

**Comment by thannaht** [comment]
Same issue here. I'm working on a ubuntu 16.04 with php7 localy installed

**Comment by Maxlab** [comment]
fixed in 1.21.4
