### ISSUE TITLE
Кастомизация

### ISSUE THREAD

**Issue by wormen** [Maxlab/stacker#2]
в контексте #1, интересует

1) как можно кастомизировать вашу поделку
2) как, например, для каждого хоста можно отдельно выставить версию php

**Comment by Maxlab** [comment]
Привет.
1. Делаете форк, кастомизируете как вам угодно - пользуетесь.
Можете предложить пуллреквестом свою сборку. После рассмотрения добавим.
В этой части у вас не должно возникнуть трудностей, но с докером разобраться придется. Stacker всего лишь конфигурация той среды, которую создает докер. 

2. Никак, этого нет в Stacker. Версий не так уж и много, на самом деле в работе еще может потребоваться 5-ая версия, и специально для этого, есть отдельная ветка legacy. Тут  https://github.com/Maxlab/stacker/tree/legacy-a2-php5-v.1.1.0 помимо 7 версии и nginx, добавлена 5 версия под апачем, который слушает 81 порт. Ставите ее и у вас сразу две версии php 5 и 7, 5 на 81 порту и 7 на 80. Очень удобно, даже переключаться не нужно.
