### ISSUE TITLE
Where do I find the error Logs? 502 Bad Gateway

### ISSUE THREAD

**Issue by regenrek** [Maxlab/stacker#24]
Hi,

where do I find the error logs ? Currently I got a 502 Bad Gateway Error with Wordpress + Woocommerce and can't find the logs where the error happens.

Could you guide me pls?

Regards

**Comment by naiwa** [comment]
I had seen the source, it's can not see the log in apache and nginx now. but you can edit by your self to configure it.

**Comment by Maxlab** [comment]
Hi! Try "stacker logs -f"
