### ISSUE TITLE
ошибка в контейнере nginx

### ISSUE THREAD

**Issue by wormen** [Maxlab/stacker#3]
после запуска сборки наблюдается ошибка
` nginx: [emerg] unexpected end of file, expecting ";" or "}" in /etc/nginx/sites-enabled/00-default:1`

но в конфигах все в порядке

**Comment by Maxlab** [comment]
Опять не по существу пишете. 
Ошибка не в контейнере, а в конфигурации, не достает закрывающей конструкции, о чем собственно и сообщает нам текст ошибки. Приведите в порядок конфиг файл, это должно помочь. Если не получается, вам стоит обратиться на форум nginx. К stacker это отношения не имеет. На примере кухни, stacker это просто комната, кухней ее делает вытяжка, плита, обеденный стол и тд. Если у вас сломалась плита, вы же не вызываете строителей.

**Comment by wormen** [comment]
так дело в том, что в конфигах я ничего не менял, была развернута та сборка, которая находится у вас в репозитории

согласно строке
`image: maxlab/nginx`
в файле `docker-compose.yml`, написал я именно туда, куда нужно, форум nginx, тут не при делах
