### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by 31H0B1eV** [Maxlab/stacker#8]
For now is impossible to run project with steps described in readme. (`\*.dev > 127.0.0.1` give command .dev not found)

As i see from video there is extra steps with `docker-compose build` etc. But its confusing when you just try follow steps in readme and got an error which tells nothing for anyone unexpirienced with docker.

Maybe it require a little update for someone who just start with docker and want to use this container?

**Comment by Maxlab** [comment]
Thanks for the feedback, we are very grateful to you, you are absolutely right this is a bug. It fixed.
